defaults:
  - fully_connected_model_base
  - _self_

activation:
  _target_: torch.nn.ReLU

bias_in_last_layer: true
hidden_layers: [64, 128, 64]
input_features: 40
normalize: false
num_classes: 40
use_batch_norm: false
