name: hpl-torch

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.9
  - cudatoolkit=11.7
  - pip
  - pytorch>=1.13
  - pre-commit
  - black
  - isort
  - flake8
  - tensorboard
  - torchvision>=0.14
  - pytorch-lightning>=1.7.7
  - hydra-core=1.2
  - matplotlib
  - ipython
  - jupyterlab
  - scikit-learn
  - rich
  - pandas
  - gitpython
  - numpy
  - seaborn
  - pillow
  - coverage
  - tqdm
  - pylint
  - sphinx
  - setuptools_scm
  - onnx
  - pip:
      - onnxruntime-gpu
      - torch-tb-profiler
      - hydra-colorlog
      - hydra-submitit-launcher
      - torchdiffeq
      - git+https://codebase.helmholtz.cloud/m-dml/unet-pytorch.git
      - git+https://codebase.helmholtz.cloud/m-dml/mdml-tools.git
