name: hpl-torch

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.10
  - pip
  - cudatoolkit
  - pytorch
  - pre-commit
  - black
  - isort
  - flake8
  - tensorboard
  - torchvision
  - pytorch-lightning
  - torchmetrics
  - matplotlib
  - ipython
  - libgcc
  - hydra-core
  - jupyterlab
  - scikit-learn
  - rich
  - pandas
  - dask
  - distributed
  - numpy
  - seaborn
  - python-dotenv
  - onnx
  - tqdm
  - pip:
      - onnxruntime
      - hydra-colorlog
      - hydra-optuna-sweeper
      - hydra-submitit-launcher
      - torchdiffeq
      - GitPython
      - "git+https://codebase.helmholtz.cloud/m-dml/unet-pytorch.git"
