defaults:
  - base_config
  - /hydra/callbacks:
      - log_git_hash
  - model: l96_base
  - da_encoder: unet_2d_1d
  - datamodule: l96_observations
  - loss: weak_4dvar
  - lightning_module: default
  - optimizer: adam
  - trainer: default
  - logger/tensorboard: tensorboard
  - callbacks/checkpoint: model_checkpoint
  - callbacks/early_stopping: early_stopping

  - override hydra/launcher: strand_single
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

  - _self_ # should be last in defaults list to override everything in structured config with here defined values

output_dir_base_path: "/gpfs/work/zinchenk/hpl/lorenz96_logs/data_assimilation"

logger:
  tensorboard:
    default_hp_metric: false # important to be False, when we want to use own hp_metrics

hydra:
  job:
    chdir: true
  sweep:
    dir: ${output_dir_base_path}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  run:
    dir: ${output_dir_base_path}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
