defaults:
  - base_config
  - /hydra/callbacks:
      - log_git_hash
  - model: l96_base
  - assimilation_network: unet_2d_1d
  - datamodule: l96_observations
  - loss: 4dvar
  - lightning_module: default.yaml
  - optimizer: adam_base
  - lightning_trainer: trainer_base
  - lightning_logger/tensorboard: tensorboard_logger_base
  - lightning_callback/checkpointing: checkpoint_callback_base
  - lightning_callback/early_stopping: early_stopping_callback_base

  - override hydra/launcher: local
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

  - _self_ # should be last in defaults list to override everything in structured config with here defined values

output_dir_base_path: "."
print_config: true

#lightning_logger:
#  tensorboard:
#    default_hp_metric: false # important to be False, when we want to use own hp_metrics
#    save_dir: "."

hydra:
  job:
    chdir: true
  sweep:
    dir: ${output_dir_base_path}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  run:
    dir: ${output_dir_base_path}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
