defaults:
  - evaluate_config
  - simulator: l96_one_level_base
  - dataset: l96_inference_dataset_base
  - _self_

output_dir_base_path: "outputs"
exp_base_dir: "/home/vadim/Dev/hidden-process-learning/levante_logs/multiran/data_assimilation/2023-05-27/21-18-22/0"
random_seed: 101
n_trials: 1000
observations_length: 100

simulator:
  forcing: 8
  method: "rk4"

dataset:
  n_integration_steps: 100
  x_grid_size: 40
  y_grid_size: 10
  time_step: 0.01
  n_spin_up_steps: 300
  additional_noise_std: 0
  n_masked_per_step: 20
  mask_fill_value: 0

hydra:
  job:
    chdir: true
  sweep:
    dir: ${output_dir_base_path}/evaluate_da/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  run:
    dir: ${output_dir_base_path}/evaluate_da/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
