_target_: "pytorch_lightning.Trainer"
enable_checkpointing: true
default_root_dir: null
gradient_clip_val: 0.0
#process_position: 0
num_nodes: 1
auto_select_gpus: true
enable_progress_bar: true
overfit_batches: 0.0
track_grad_norm: -1
check_val_every_n_epoch: 1
fast_dev_run: false
accumulate_grad_batches: 1
max_epochs: 1
min_epochs: 1
max_steps: -1
min_steps: null
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
val_check_interval: 1.0
log_every_n_steps: 50
sync_batchnorm: false
precision: 32
#weights_summary: "top"
weights_save_path: null
num_sanity_val_steps: 2
resume_from_checkpoint: null
profiler: null
benchmark: false
deterministic: false
auto_lr_find: false
replace_sampler_ddp: true
detect_anomaly: true
auto_scale_batch_size: false
plugins: null
amp_backend: "native"
amp_level: null
move_metrics_to_cpu: false
accelerator: null
devices: null
