defaults:
  - l96_datamodule_base
  - dataset: l96_dataset_base
  - simulator: l96_base
  - _self_

save_training_data_dir: null
load_training_data_dir: null
data_amount: 2000
train_validation_split: 0.75
shuffle_train: true
shuffle_valid: false
batch_size: 32
drop_last_batch: false
num_workers: 10
pin_memory: false

dataset:
  x_grid_size: 40
  y_grid_size: 10
  time_step: 0.01
  n_spin_up_steps: 300
  additional_noise_std: 0
  n_masked_per_step: 30
  mask_fill_value: 0
  rollout_length: 25
  window_length: 25

simulator:
  simulator_type: "one_level"
  forcing: 8.0
  method: "rk4"
